### PR TITLE
Choose registry when installing strong-build

### PR DESCRIPTION
**Pull request by xuqingfeng**
Even only install `strong-build` through official registry is painful on `dev` box.

### CODE REVIEW

**Comment by zbal** [comment]
Seems OK to me, just confirm / test 2 things:
- will the ARGS command invalidate the cache of the former runs?
- will changing the ARGS invalidate the old cache?

**Comment by zbal** [comment]
Should we - for the sake of avoiding to manage both strong-pm images and the code in the same file, use an in-between container? There we don't even need to bother having different mirrors for installing the builder or strong-pm; we would only have the REGISTRY for the code.

Typically:

- create a **new** node-builder container based on node container - that we can then push on hub.docker
- builder is based (FROM) on node-builder container (like the former approach, we still need to download the 1st version of node - here, we'd fetch the 1st version of node-builder
- create a **new** strong-pm-runner container - that we can then push on hub.docker
- docker-runner is based on strong-pm-runner

**Comment by zbal** [comment]
Can do 1 strong-pm based container with:
- strong-pm, strong-build and strong-deploy
- with the strong-pm user

Then:
- builder 
  - based on ^ 
  - copy the tempate, etc.
- runner
  - based on ^
  - expose + workdir + etc.

**Comment by xuqingfeng** [comment]
close in favour of #3

**Comment by xuqingfeng** [comment]
About the `ARGS` cache issue: https://docs.docker.com/engine/reference/builder/#impact-on-build-caching

**Pull request closed without merging**
