### PR TITLE
Change base images

### PR DESCRIPTION
**Pull request by xuqingfeng**
https://github.com/wiredcraft-ops/strong-base
https://hub.docker.com/r/boratbot/strong-base

`git push` will trigger build in docker hub

### CODE REVIEW

**Comment by zbal** [comment]
@xuqingfeng - why changing `strong-pm` to `strong-base`, what is the benefit? `strong-pm` is quite standard for a user that will run the `strong-pm` process.

If this is to match the image name - I'd actually rather we change the image name to `strong-pm-base` to avoid the confusion

**Comment by xuqingfeng** [comment]
@zbal we also have `strong-build` `strong-deploy`, it's 'unfair' 🤔 .

**Comment by zbal** [comment]
Those are only binaries / tools being used - `strong-pm` is what is gonna run eventually for the lifetime of those containers. 

You can keep the base name of the container as `strong-base`, but change the name of the folders/user as `strong-pm`.

**Comment by xuqingfeng** [comment]
@zbal fair enough

**Pull request closed without merging**
